config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'pages#home'

   get "movies/new", to: "movies#new"
   get "movies/search_movie", to: "movies#search_movie", as: :search_movie
   get "movies/choose_movie", to: "movies#choose_movie", as: :choose_movie
   post "movies", to: "movies#create"

   get "user/:id/wishlist/show", to: "wishlists#show", as: :wishlist

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :imdb_id, presence: true, uniqueness: true
  has_many :wishlist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wishlists
  has_many :movies, through: :wishlists
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :movie, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @movie = Movie.new
  end

  def create

    movie = Movie.find_by(title: movie_params[:title])

    if movie.nil?
      movie = Movie.new(movie_params)
      movie.save!
    end

    user = User.find(current_user.id)

    @wishlist = Wishlist.find_by(user_id: user.id, movie_id: movie.id)

    if @wishlist.nil?
      @wishlist = Wishlist.new(user_id: user.id, movie_id: movie.id)
    end

    respond_to do |format|
      if @wishlist.save!
        format.html { render "pages/homes" }
        format.json { render json:success_data }
      else
        format.html { render "pages/homes" }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  def choose_movie
    wishlist = Wishlist.where(user_id: current_user.id)
    choosed_id_movie = wishlist.sample.movie_id
    @choosed_movie = Movie.find(choosed_id_movie)
  end

    private

    def movie_params
      params.require(:movie).permit(:title, :imdb_id, :url_image)
    end

    def success_data
      {
        inserted_item: render_to_string(partial: 'movies/success.html')
      }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # def home
  #   @user = current_user
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clicknmovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <div class="diagonal-box">
    <div class="container">
	    <div class="content">
        <body>

          <%= render 'shared/navbar' %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </body>
      </div>
    </div>
  </div>

</html>

app/views/movies/_success.html.erb
<%= @wishlist.user.id %>

app/views/movies/choose_movie.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div data-controller="search">
        <h3> <%=  @choosed_movie.title %> <h3> <br>
        <% if @choosed_movie.url_image.nil? %>
          <%= image_tag("no-poster-available.png", size: "260x370") %>
        <% else %>
          <%= image_tag @choosed_movie.url_image, size: "260x380" %>
        <% end %>
    </div>
    <div class="p-2 mt-5">
      <%= link_to "Choisir un autre film", choose_movie_path, class: "btn btn-lg btn-primary" %>
      </div>
    <div class="p-2 mt-5">
      <%= link_to "Retour", root_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <%= form_for(@movie) do |f| %>
      <%= f.text_field :title %>

      <div class="p-2 mt-2">
        <%= f.submit "Chercher un film", class: "btn btn-lg btn-primary" %>
      </div>

    <% end %>
    </div>
</div>

app/views/movies/search_movie.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div data-controller="search">
      <input data-search-target="title" type="text">
        <button data-action="click->search#movie" class="btn btn-primary p-2 mt-2" data-search-key-param="<%=ENV['IMDB_KEY_API']%>" >Recherche</button>
    </div>
    <div class="col-md-12 text-center">
      <ul id="results" class="list-inline pt-5"></ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="text-center">

  <% if current_user %>
    <div class="p-2 mt-5">
      <%= link_to "Voir ma liste de films", wishlist_path(current_user), class: "btn  btn-lg btn-primary" %><br>
    </div>

    <div class="p-2 mt-5">
      <%= link_to "Ajouter un film", search_movie_path, class: "btn btn-lg btn-primary" %>
    </div>

    <div class="p-2 mt-5">
      <%= link_to "Choisir un film", choose_movie_path, class: "btn btn-lg btn-primary" %>
    </div>
  <% else %>
    <div class="p-2 mt-5">
      <%= link_to "Connexion", new_user_session_path, class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>

</div>

app/views/shared/_navbar.html.erb
    <nav>
      <div class="navbar">
        <div class="container nav-container">
            <input class="checkbox" type="checkbox" name="" id="" />
            <div class="hamburger-lines">
              <span class="line line1"></span>
              <span class="line line2"></span>
              <span class="line line3"></span>
            </div>
          <div class="logo">
            <h1>Clicknmovie</h1>
          </div>
          <div class="menu-items">

            <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
          </div>
        </div>
      </div>
    </nav>

app/views/wishlists/show.html.erb
<div class="row banner-succes">
  <div class="col-md-12 text-center">
    <% if @user.movies.empty? %>
      Aucun film dans ta liste <br>
      <div class="p-2 mt-5">
        <%= link_to "Ajouter un film", search_movie_path, class: "btn btn-lg btn-primary" %>
      </div>
    <% else%>
      <div class="p-2 mt-5">
        <% @user.movies.each do |movie|%>
            <h3> <%= movie.title %> <h3> <br>
            <% if movie.url_image.nil? %>
              <%= image_tag("no-poster-available.png", size: "260x370") %>
            <% else %>
              <%= image_tag movie.url_image, size: "260x380" %> <br>
            <% end %>
        <% end %>
      </div>
      <%= link_to "Retour", root_path, :class => "btn btn-lg btn-primary" %><br>
    <% end %>

  </div>
</div>